- name: 'update the LDM registry (1)'
  command: >
    ./bin/regutil -s {{ item.val }} {{ item.key }}
    chdir={{ ldm_home }}
  sudo_user: ldm
  with_items:
    - key: /hostname
      val: "{{ ldm_host }}}"
    - key: /log/file
      val: "{{ ldm_log_file }}"

- name: 'update the LDM registry (2)'
  command: >
    ./bin/regutil -u {{ item.val }} {{ item.key }}
    chdir={{ ldm_home }}
  sudo_user: ldm
  with_items:
    - key: /server/port
      val: "{{ ldm_port }}"
    - key: /log/counts
      val: "{{ ldm_log_counts }}"

- name: 'copy ldmd.conf'
  template: >
    src=ldmd.conf.j2
    dest={{ ldm_home }}/etc/ldmd.conf
  sudo_user: ldm

- name: 'copy pqact.conf'
  template: >
    src=pqact.conf.j2
    dest={{ ldm_home }}/etc/pqpact.conf
  sudo_user: ldm
