- name: 'ensure required packages are installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - pax
    - libxml2-dev
    - zlib1g-dev
    - expect

- name: 'fetch the LDM source'
  get_url: >
    url="ftp://ftp.unidata.ucar.edu/pub/ldm/ldm-{{ ldm_version }}.tar.gz"
    dest=/tmp/ldm-{{ ldm_version }}.tar.gz
  sudo_user: ldm

- name: 'unpack the LDM source'
  shell: >
    gunzip -c /tmp/ldm-{{ ldm_version }}.tar.gz | pax -r '-s:/:/src/:'
    chdir={{ ldm_home }}
  sudo_user: ldm

- name: 'copy an expect script'
  copy: src=configure.expect
        dest={{ ldm_home }}/ldm-{{ ldm_version }}/src/configure.expect
        mode=0775
  sudo_user: ldm

- name: 'run a configure script via the expect script'
  command: >
    ./configure.expect
    chdir={{ ldm_home }}/ldm-{{ ldm_version }}/src
  sudo_user: ldm

- name: 'make install && make clean'
  shell: >
    make install && make clean
    chdir={{ ldm_home }}/ldm-{{ ldm_version }}/src
  sudo_user: ldm

- name: 'make root-actions'
  command: >
    make root-actions
    chdir={{ ldm_home }}/ldm-{{ ldm_version }}/src

- name: 'register the host name'
  command: >
    ./bin/regutil -s {{ ldm_host }} /hostname
    chdir={{ ldm_home }}
  sudo_user: ldm

- name: 'copy an init script'
  template: >
    src=ldmd.j2
    dest=/etc/init.d/ldmd
    owner=root group=root mode=0755

- name: 'start ldmd and have it start at system startup'
  service: name=ldmd state=started enabled=yes
